#!/usr/bin/env bash
#
# This script takes a directory containing some Retrosheet event log
# archives (eg: 2008ml.zip, 2007ml.zip) and loads all data into a CSV file
# via Chadwick. Specify the input directory and output file as arguments.
#
# You must have Chadwick's 'cwevent' utility properly installed. See:
#   http://chadwick.sourceforge.net
#
# Retrosheet event logs can be downloaded from:
#   http://www.retrosheet.org/game.htm
#
# Example usage:
#   events_to_csv ~/eventlogs events.csv
#

show_usage() {
  echo "Usage: events_to_csv INPUT_DIR [OUTPUT_FILE]"
}

# exit if no INTPUT_DIR given
if [[ $1 == "" ]]; then
  show_usage
  exit 1
else
  ZIPDIR=$1
fi

# choose a reasonable default OUTPUT_FILE if none given
if [[ $2 == "" ]]; then
  OUTFILE="$(pwd)/events.csv"
else
  OUTFILE="$(pwd)/$2"
fi

TMPDIR="tmp$RANDOM"

# unzip archives to temp dir
cd $ZIPDIR
unzip \*.zip -d $TMPDIR

# run each event file through Chadwick
cd $TMPDIR
for f in *.EV*; do
  cwevent -f 0-96 -y ${f:0:4} $f >> $OUTFILE
done

# clean up
rm *
cd ..
rmdir $TMPDIR

exit 0
