#!/usr/bin/env ruby

require 'rubygems'
require 'nokogiri'

module ArrayToHash
  def to_hash(a); Hash[*a.flatten]; end
end

class BatterGame < Nokogiri::XML::SAX::Document
  include ArrayToHash
  def start_element(e, a)
    case e
    when 'boxscore'
      a = to_hash(a)
      @game_id = a['game_id']
      @game_date = a['date'].gsub('/', '-')
      @home_team = a['home']
    when 'players'
      a = to_hash(a)
      @team = a['team']
    when 'player'
      a = to_hash(a)
      @player_id = a['id']
    when 'batting'
      a = to_hash(a)
      puts [
        @player_id,
        @game_date[0...4],        # year
        "",                       # league
        @team,                    # team
        @game_date,               # game date
        @home_team,               # home team
        @game_id[-1..-1],         # game_number
        a['ab'].to_i > 0 ? 1 : 0, # 1=player batted, 0=did not bat
        a['ab'],
        a['r'],
        a['h'],
        a['d'],
        a['t'],
        a['hr'],
        a['bi'],
        a['sb'],
        a['cs'],
        a['bb'],
        a['so'],
        a['ibb'],
        a['hp'],
        a['sh'],
        a['sf'],
        a['gdp']
      ].map{ |i| i.to_s == i.to_i.to_s ? (i.to_i < 0 ? "" : i) : "\"#{i}\"" }.join(',')
    end
  end
end

parser = Nokogiri::XML::SAX::Parser.new(BatterGame.new)
parser.parse_file(File.join(ARGV[0]))


# load into MySQL database
#LOAD DATA LOCAL INFILE '...' INTO TABLE batting_games FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
#
# convert Retrosheet player ids to BDB ids
#UPDATE batting_games bg INNER JOIN players p ON bg.player_id = p.retro_id SET bg.player_id = p.id;

