#!/usr/bin/env bash
#
# Download baseball data (XML) files from MLBAM.
#
# Requires a shell with a `date` command that accepts the -d option
# for specifying a custom date (works on Ubuntu, does not work on OSX).
#

usage() {
  echo "Usage:"
  printf "  %s [options] [output_dir]\n" $(basename $0) >&2
  echo ""
  echo "Options:"
  echo "  -y <year>    Year for which to download files (default: $(date +%Y))."
  echo "  -l <league>  League: mlb, milb, etc (default: mlb)."
  echo "  -t           Include today's files (othewise stops at yesterday)."
  echo "  -v           Be verbose (display downloaded files)."
  echo "  -w           Overwrite existing files."
  echo "  -h           Print this help."
}

# takes a timestamp and format string
formatdate() {
  date -d "1970-01-01 $1 sec" +"$2"
}

# month_xx/day_xx portion of URL or path for the given date
datepath() {
  formatdate "$1" "month_%m/day_%d"
}

# base MLBAM URL for a given date
dateurl() {
  echo "$baseurl/year_$year/$(datepath $1)"
}

# ids of games played on the given date
gameids() {
  curl -s "$(dateurl $1)/"                |
  grep 'gid_[0-9]\{4\}_[0-9]\{2\}_[0-9]\{2\}' |
  sed 's:.*href="\([^/"]*\)/".*:\1:'
}

# files to download for each game
datafiles() {
  echo "boxscore.xml"
  echo "players.xml"
  echo "game.xml"
  echo "gameday_Syn.xml"
  echo "linescore.xml"
}

year=$(date +%Y)
league=mlb
overwrite=
today=
verbose=

while getopts "y:l:vwth" opt; do
  case $opt in
    y) year="$OPTARG" ;;
    l) league="$OPTARG" ;;
    t) today=true ;;
    v) verbose=true ;;
    w) overwrite=true ;;
    h) usage; exit 0 ;;
    *) usage; exit 1 ;;
  esac
done
shift $(( OPTIND - 1 ))

baseurl="http://gdx.mlb.com/components/game/$league"
[ -z $1 ] && outputdir="./mlbam" || outputdir="$1"

# set first and last dates to fetch (seconds since 1970-01-01)
firstdate=$(date -d "$year-02-01" +%s)
if [ "$year" -eq $(date +%Y) ]; then
  lastdate=$(date +%s)
  [ $today ] || ((lastdate -= 60*60*24))
else
  lastdate=$(date -d "$year-11-10" +%s)
fi

echo "Downloading data for $league ($(formatdate "$firstdate" "%b %d") - \
$(formatdate "$lastdate" "%b %d"), $year) to $outputdir"

d="$firstdate"

while true; do
  for gid in $(gameids $d); do
    [ $verbose ] && echo "Processing game $gid"
    gameurl="$(dateurl $d)/$gid"
    gamedir="$outputdir/$(datepath $d)/$gid"
    mkdir -p "$gamedir"
    for file in $(datafiles); do
      if [ ! -f "$gamedir/$file" ] || [ $overwrite ]; then
        [ $verbose ] && echo "  $file"
        curl -s "$gameurl/$file" > "$gamedir/$file"
      fi
    done
    sleep 1 # be a little polite
  done
  if [ "$(formatdate $d %F)" == "$(formatdate $lastdate %F)" ]; then
    break
  else
    ((d += 60*60*24))
  fi
done
