#!/usr/bin/env bash
#
# Get a diff between two revisions of a MLBAM XML file. Takes the hash of the
# commit of interest and the filename.
#

iflag=

while getopts 'i' OPTION
do
  case $OPTION in
  i) iflag=1
    ;;
  ?) printf "Usage: %s [-i] <commit> <filename>\n" $(basename $0) >&2
    exit 2
    ;;
  esac
done
shift $(($OPTIND - 1))

commit="$1"
filepath="$2"
tmpdir="tmp$RANDOM"

if [ ! -e "$filepath" ]; then
  echo "File not found."
  exit 1
fi

mkdir "$tmpdir"

git co $commit^ "$filepath"
xmllint --format "$filepath" > "$tmpdir/old.xml"

git co $commit "$filepath"
xmllint --format "$filepath" > "$tmpdir/new.xml"

git co HEAD "$filepath"

if [ "$iflag" ]; then
  sort "$tmpdir/old.xml" -o "$tmpdir/old.xml"
  sort "$tmpdir/new.xml" -o "$tmpdir/new.xml"
fi

diff -u "$tmpdir/old.xml" "$tmpdir/new.xml"

rm "$tmpdir"/*
rmdir "$tmpdir"
