#!/usr/bin/env bash
#
# Get a diff between two revisions of a MLBAM XML file.
#

usage(){
  echo "Usage:"
  printf "  %s [-i] [-c <commit>] <filename>\n" $(basename $0) >&2
  echo ""
  echo "Options:"
  echo "  -i           ignore line order"
  echo "  -c <commit>  look at changes in the given commit (default: HEAD)"
}

iflag=
commit=HEAD

while getopts 'ic:' OPTION; do
  case $OPTION in
    c) commit=$OPTARG ;;
    i) iflag=1 ;;
    ?) usage; exit 2 ;;
  esac
done
shift $(($OPTIND - 1))

filepath="$1"
tmpdir="tmp$RANDOM"

if [ ! -e "$filepath" ]; then
  echo "File not found."
  exit 1
fi

mkdir "$tmpdir"

git co $commit^ "$filepath"
xmllint --format "$filepath" > "$tmpdir/old.xml"

git co $commit "$filepath"
xmllint --format "$filepath" > "$tmpdir/new.xml"

git co HEAD "$filepath"

if [ "$iflag" ]; then
  sort "$tmpdir/old.xml" -o "$tmpdir/old.xml"
  sort "$tmpdir/new.xml" -o "$tmpdir/new.xml"
fi

diff -u "$tmpdir/old.xml" "$tmpdir/new.xml"

rm "$tmpdir"/*
rmdir "$tmpdir"
